Migrate TEST_MAPPING options -> Android.bp
This is the second of several cls to start the migration of options in
TEST_MAPPING files to being specified in Android.bp files.

These tests already fail and will not pass the SLO checker, but
we will get an exception.

https://android-build.corp.google.com/test_investigate/invocation/I90500010261340262/test/TR68129237142233643/
java.lang.SecurityException: You either need MANAGE_USERS or CREATE_USERS permission to: query users
	at com.android.server.pm.UserManagerService.checkCreateUsersPermission(UserManagerService.java:3824)
	at com.android.server.pm.UserManagerService.getUsers(UserManagerService.java:1362)
	at com.android.server.pm.UserManagerService.getUsers(UserManagerService.java:1355)
	at com.android.server.pm.UserManagerServiceUserInfoTest.setup(UserManagerServiceUserInfoTest.java:102)

The overall goal is to get local (atest) runs closer to CI runs of the
tests and split FrameworksServicesTests at runtime to different owners
can be assigned to different parts of the test.

Step 1) Introduce new modules and list them in TEST_MAPPING postsubmit
Step 2) Wait a week for SLO checker to accept the new modules.
Step 3) Replace current presubmit TEST_MAPPING entries with the module
names.
This was hand-crafted cl, not using the migration script yet.
I am starting with one directory that has several TEST_MAPPING files

Migration Plan Doc: https://docs.google.com/document/d/1x3w-BvKO3E-GbY8YOSBuzJC6-pkLkuhfjSyZ1hJQBYM/edit?tab=t.0#heading=h.17wg41voij6q

Test: atest FrameworksServicesTests_pm_presubmit
Test: atest -p .:presubmit
Change-Id: I5227f9c4b66e62e2f858b796cfb8aa7b1eea806c
Flag: TEST_ONLY
Test-Mapping-Slo-Bypass-Bug: b/335015078

Former-commit-id: 960e03f6c0f1bbe304a3bad0eeb35b8f249612b5 [formerly a895d3a1280d6285367d03ce8702cfe7e68e4f8a]
Former-commit-id: 8b85ef3e587269ac1bbaee33f56278c8f30d8ce1